import Head from "next/head";
import BaseLayout from "../components/layouts/base";
import Topbar from "../components/topbar";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Movie Time</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen">
        <Topbar />
        <div className="heading__text text-white text-3xl flex justify-center uppercase">
          <h1>See Details of your desire movies...</h1>
        </div>
      </main>
    </div>
  );
}
